# -*- coding: utf-8 -*-
"""translator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YfPXvrIYQvAU5EIjXAoVvwZ-tVUPBqo0
"""

!pip install googletrans==4.0.0-rc1

from googletrans import Translator

# Initialize the Translator
translator = Translator()

# Text to translate and target language
text = "Hello, My name is Neha."
target_language = 'fr'  # French

# Translate
translated_text = translator.translate(text, dest=target_language)

# Print the result
print("Original Text:", text)
print("Translated Text:", translated_text.text)